sqlite: &sqlite
  adapter: sqlite3
  database: db/<%= Rails.env %>.sqlite3

defaults: &defaults
  pool: 5
  timeout: 5000
  encoding: utf8
  <<: *<%= ENV['RAILS_DB'] || "sqlite" %>

development:
  <<: *defaults

test: &test
  <<: *defaults

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: < %=ENV['OPENSHIFT_APPNAME']%>
  host: < %=ENV['$OPENSHIFT_POSTGRESQL_DB_HOST']%>
  port: < %=ENV['$OPENSHIFT_POSTGRESQL_DB_PORT']%>
  username: < %=ENV['OPENSHIFT_POSTGRESQL_DB_USERNAME']%>
  password: < %=ENV['OPENSHIFT_POSTGRESQL_DB_PASSWORD']%>  
  
  min_messages: ERROR
  reconnect: false